$TempOriginalFileBeingDebuggedFileName = "dstore"
$TempOriginalFileBeingDebuggedFileFolder = "D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade"
$TempOriginalFileBeingDebuggedFilePath = "D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3"
AutoIt_Debugger_LoadFile("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore")
AutoIt_Debugger_DebugFile(@ScriptFullPath)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 1, False, @error, @extended)
#Include "D:\Program Files\AutoIt3\Include\array.au3"
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 1, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 2, False, @error, @extended)
func _dstorefindindex($dstore,$nameofsection)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 2, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$nameofsection", $nameofsection, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 3, False, @error, @extended)
	dim $index = -1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 3, False, @error, @extended)
AutoIt_Debugger_SendVariable("$index", $index, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 4, False, @error, @extended)
	if StringInStr($dstore,@crlf) <> 0 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 4, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 5, False, @error, @extended)
		$dstore = StringSplit($dstore,@crlf)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 5, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 6, False, @error, @extended)
	ElseIf StringInStr($dstore,@lf) <> 0 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 6, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 7, False, @error, @extended)
		$dstore = StringSplit($dstore,@lf)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 7, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 8, False, @error, @extended)
	Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 8, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 9, False, @error, @extended)
		$dstore = StringSplit($dstore,@cr)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 9, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 10, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 10, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 11, False, @error, @extended)
	dim $todelete[10000]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 11, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 12, False, @error, @extended)
	$todelete[0] = 0
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 12, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 13, False, @error, @extended)
	for $i = 1 to $dstore[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 13, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 14, False, @error, @extended)
		if $dstore[$i] = "" Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 14, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 15, False, @error, @extended)
			$todelete[0] = $todelete[0] + 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 15, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 16, False, @error, @extended)
			$todelete[$todelete[0]] = $i
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 16, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 17, False, @error, @extended)
		EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 17, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 18, False, @error, @extended)
	Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 18, False, @error, @extended)
;~ 	MsgBox(0,"dsdebug " & UBound($dstore),$index & " " & $section)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 20, False, @error, @extended)
	for $i = 1 to $todelete[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 20, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 21, False, @error, @extended)
		_ArrayDelete($dstore,$todelete[$i]-($i-1))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 21, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 22, False, @error, @extended)
		$dstore[0] = $dstore[0] - 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 22, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 23, False, @error, @extended)
	Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 23, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 24, False, @error, @extended)
	for $i = 1 to $dstore[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 24, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 25, False, @error, @extended)
		if StringInStr($dstore[$i],$nameofsection & "|") <> 0 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 25, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$nameofsection", $nameofsection, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 26, False, @error, @extended)
			$index = $i
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 26, False, @error, @extended)
AutoIt_Debugger_SendVariable("$index", $index, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 27, False, @error, @extended)
			ExitLoop
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 27, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 28, False, @error, @extended)
		EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 28, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 29, False, @error, @extended)
	Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 29, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 30, False, @error, @extended)
	Return $index
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 30, False, @error, @extended)
AutoIt_Debugger_SendVariable("$index", $index, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 31, False, @error, @extended)
EndFunc
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 31, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 32, False, @error, @extended)
func _dstorestorevalue($dstore,$section,$value)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 32, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$section", $section, @error, @extended)
AutoIt_Debugger_SendVariable("$value", $value, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 33, False, @error, @extended)
	$index = _dstorefindindex($dstore,$section)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 33, False, @error, @extended)
AutoIt_Debugger_SendVariable("$index", $index, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$section", $section, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 34, False, @error, @extended)
	if StringInStr($dstore,@crlf) <> 0 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 34, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 35, False, @error, @extended)
		$dstore = StringSplit($dstore,@crlf)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 35, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 36, False, @error, @extended)
	ElseIf  StringInStr($dstore,@lf) <> 0 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 36, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 37, False, @error, @extended)
		$dstore = StringSplit($dstore,@lf)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 37, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 38, False, @error, @extended)
	Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 38, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 39, False, @error, @extended)
		$dstore = StringSplit($dstore,@cr)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 39, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 40, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 40, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 41, False, @error, @extended)
	dim $todelete[10000]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 41, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 42, False, @error, @extended)
	$todelete[0] = 0
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 42, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
;~ 	_ArrayDisplay($dstore,"p1st")
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 44, False, @error, @extended)
	for $i = 1 to $dstore[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 44, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 45, False, @error, @extended)
		if $dstore[$i] = "" Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 45, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 46, False, @error, @extended)
			$todelete[0] = $todelete[0] + 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 46, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 47, False, @error, @extended)
			$todelete[$todelete[0]] = $i
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 47, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 48, False, @error, @extended)
		EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 48, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 49, False, @error, @extended)
	Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 49, False, @error, @extended)
;~ 	MsgBox(0,"dsdebug " & UBound($dstore),$index & " " & $section)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 51, False, @error, @extended)
	for $i = 1 to $todelete[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 51, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 52, False, @error, @extended)
		_ArrayDelete($dstore,$todelete[$i]-($i-1))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 52, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 53, False, @error, @extended)
		$dstore[0] = $dstore[0] - 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 53, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 54, False, @error, @extended)
	Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 54, False, @error, @extended)
;~ 	_ArrayDisplay($dstore,"1st")
;~ 	MsgBox(0,"debug 1st",$section & "|" & $value)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 57, False, @error, @extended)
	if $index <> -1 and UBound($dstore) >= $index Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 57, False, @error, @extended)
AutoIt_Debugger_SendVariable("$index", $index, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$index", $index, @error, @extended)
;~ 		MsgBox(0,"dsdebug1 " & UBound($dstore),$index & " " & $section & @lf & $value)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 59, False, @error, @extended)
		$dstore[$index] = $section & "|" & $value
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 59, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$index", $index, @error, @extended)
AutoIt_Debugger_SendVariable("$section", $section, @error, @extended)
AutoIt_Debugger_SendVariable("$value", $value, @error, @extended)
;~ 		MsgBox(0,"dsdebug1.1",$dstore[$index])
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 61, False, @error, @extended)
	Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 61, False, @error, @extended)
;~ 		MsgBox(0,"dsdebug2 " & UBound($dstore),$index & " " & $section)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 63, False, @error, @extended)
		_ArrayAdd($dstore,$section & "|" & $value)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 63, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$section", $section, @error, @extended)
AutoIt_Debugger_SendVariable("$value", $value, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 64, False, @error, @extended)
		$dstore[0] = $dstore[0] + 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 64, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
;~ 		_ArrayDisplay($dstore,"2nd")
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 66, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 66, False, @error, @extended)
;~ 	_ArrayDisplay($dstore,"2nd")
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 68, False, @error, @extended)
	dim $dt
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 68, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dt", $dt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 69, False, @error, @extended)
	for $i = 1 to $dstore[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 69, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 70, False, @error, @extended)
		$dt = $dt & $dstore[$i] & @CRLF
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 70, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dt", $dt, @error, @extended)
AutoIt_Debugger_SendVariable("$dt", $dt, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
;~ 		MsgBox(0,$i & "\" & $dstore[0],$dt & " dstore[$i] " & $dstore[$i])
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 72, False, @error, @extended)
	Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 72, False, @error, @extended)
;~ 	MsgBox(0,"dsdebugdt",$dt)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 74, False, @error, @extended)
	Return $dt
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 74, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dt", $dt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 75, False, @error, @extended)
EndFunc
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 75, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 76, False, @error, @extended)
func _dstoregetvalue($dstore,$section)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 76, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$section", $section, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 77, False, @error, @extended)
	$index = _dstorefindindex($dstore,$section)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 77, False, @error, @extended)
AutoIt_Debugger_SendVariable("$index", $index, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$section", $section, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 78, False, @error, @extended)
	if $index = -1 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 78, False, @error, @extended)
AutoIt_Debugger_SendVariable("$index", $index, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 79, False, @error, @extended)
		return -1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 79, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 80, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 80, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 81, False, @error, @extended)
	if StringInStr($dstore,@crlf) <> 0 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 81, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 82, False, @error, @extended)
		$dstore = StringSplit($dstore,@crlf)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 82, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 83, False, @error, @extended)
	ElseIf  StringInStr($dstore,@lf) <> 0 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 83, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 84, False, @error, @extended)
		$dstore = StringSplit($dstore,@lf)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 84, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 85, False, @error, @extended)
	Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 85, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 86, False, @error, @extended)
		$dstore = StringSplit($dstore,@cr)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 86, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 87, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 87, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 88, False, @error, @extended)
	dim $todelete[10000]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 88, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 89, False, @error, @extended)
	$todelete[0] = 0
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 89, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 90, False, @error, @extended)
	for $i = 1 to $dstore[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 90, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 91, False, @error, @extended)
		if $dstore[$i] = "" Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 91, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 92, False, @error, @extended)
			$todelete[0] = $todelete[0] + 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 92, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 93, False, @error, @extended)
			$todelete[$todelete[0]] = $i
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 93, False, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 94, False, @error, @extended)
		EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 94, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 95, False, @error, @extended)
	Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 95, False, @error, @extended)
;~ 	MsgBox(0,"dsdebug " & UBound($dstore),$index & " " & $section)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 97, False, @error, @extended)
	for $i = 1 to $todelete[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 97, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 98, False, @error, @extended)
		_ArrayDelete($dstore,$todelete[$i]-($i-1))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 98, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$todelete", $todelete, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 99, False, @error, @extended)
		$dstore[0] = $dstore[0] - 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 99, False, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 100, False, @error, @extended)
	Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 100, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 101, False, @error, @extended)
	$temp1 = $dstore[$index]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 101, False, @error, @extended)
AutoIt_Debugger_SendVariable("$temp1", $temp1, @error, @extended)
AutoIt_Debugger_SendVariable("$dstore", $dstore, @error, @extended)
AutoIt_Debugger_SendVariable("$index", $index, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 102, False, @error, @extended)
	$temp1 = StringSplit($temp1,"|")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 102, False, @error, @extended)
AutoIt_Debugger_SendVariable("$temp1", $temp1, @error, @extended)
AutoIt_Debugger_SendVariable("$temp1", $temp1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 103, False, @error, @extended)
	dim $temp
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 103, False, @error, @extended)
AutoIt_Debugger_SendVariable("$temp", $temp, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 104, False, @error, @extended)
	if $temp1[0] = 2 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 104, False, @error, @extended)
AutoIt_Debugger_SendVariable("$temp1", $temp1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 105, False, @error, @extended)
		$temp = $temp1[2]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 105, False, @error, @extended)
AutoIt_Debugger_SendVariable("$temp", $temp, @error, @extended)
AutoIt_Debugger_SendVariable("$temp1", $temp1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 106, False, @error, @extended)
	Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 106, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 107, False, @error, @extended)
		for $i = 2 to $temp1[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 107, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$temp1", $temp1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 108, False, @error, @extended)
			if $i <> $temp1[0] then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 108, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$temp1", $temp1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 109, False, @error, @extended)
				$temp = $temp & $temp1[$i] & "|"
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 109, False, @error, @extended)
AutoIt_Debugger_SendVariable("$temp", $temp, @error, @extended)
AutoIt_Debugger_SendVariable("$temp", $temp, @error, @extended)
AutoIt_Debugger_SendVariable("$temp1", $temp1, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 110, False, @error, @extended)
			Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 110, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 111, False, @error, @extended)
				$temp = $temp & $temp1[$i]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 111, False, @error, @extended)
AutoIt_Debugger_SendVariable("$temp", $temp, @error, @extended)
AutoIt_Debugger_SendVariable("$temp", $temp, @error, @extended)
AutoIt_Debugger_SendVariable("$temp1", $temp1, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 112, False, @error, @extended)
			EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 112, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 113, False, @error, @extended)
		Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 113, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 114, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 114, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 115, False, @error, @extended)
	return $temp
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 115, False, @error, @extended)
AutoIt_Debugger_SendVariable("$temp", $temp, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 116, False, @error, @extended)
EndFunc
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\dstore.au3", "dstore", 116, False, @error, @extended)
