$TempOriginalFileBeingDebuggedFileName = "em"
$TempOriginalFileBeingDebuggedFileFolder = "D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade"
$TempOriginalFileBeingDebuggedFilePath = "D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3"
AutoIt_Debugger_LoadFile("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em")
AutoIt_Debugger_DebugFile(@ScriptFullPath)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 1, False, @error, @extended)
#Region ;**** Directives created by AutoIt3Wrapper_GUI ****
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 1, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 2, False, @error, @extended)
#AutoIt3Wrapper_Run_Obfuscator=y
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 2, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 3, False, @error, @extended)
#Obfuscator_Parameters=/cf 0
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 3, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 4, False, @error, @extended)
#EndRegion ;**** Directives created by AutoIt3Wrapper_GUI ****
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 4, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 5, False, @error, @extended)
#include-once
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 5, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 6, False, @error, @extended)
Local $rt
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 6, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 7, False, @error, @extended)
Local $rt1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 7, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt1", $rt1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 8, False, @error, @extended)
Local $ct
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 8, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ct", $ct, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 9, False, @error, @extended)
Dim $a1, $a2
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 9, False, @error, @extended)
AutoIt_Debugger_SendVariable("$a1", $a1, @error, @extended)
AutoIt_Debugger_SendVariable("$a2", $a2, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 10, False, @error, @extended)
For $i = 0 To 31
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 10, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 11, False, @error, @extended)
	If $i = 10 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 11, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 12, False, @error, @extended)
		$a1 = $a1 & Chr(10) & Chr(13)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 12, False, @error, @extended)
AutoIt_Debugger_SendVariable("$a1", $a1, @error, @extended)
AutoIt_Debugger_SendVariable("$a1", $a1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 13, False, @error, @extended)
	ElseIf $i = 13 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 13, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 14, False, @error, @extended)
		ContinueLoop
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 14, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 15, False, @error, @extended)
	Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 15, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 16, False, @error, @extended)
		$a1 = $a1 & Chr($i)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 16, False, @error, @extended)
AutoIt_Debugger_SendVariable("$a1", $a1, @error, @extended)
AutoIt_Debugger_SendVariable("$a1", $a1, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 17, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 17, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 18, False, @error, @extended)
Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 18, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 19, False, @error, @extended)
For $i = 127 To 255
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 19, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 20, False, @error, @extended)
	$a2 = $a2 & Chr($i)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 20, False, @error, @extended)
AutoIt_Debugger_SendVariable("$a2", $a2, @error, @extended)
AutoIt_Debugger_SendVariable("$a2", $a2, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 21, False, @error, @extended)
Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 21, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 22, False, @error, @extended)
Func sen($pt, $lol = "")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 22, False, @error, @extended)
AutoIt_Debugger_SendVariable("$pt", $pt, @error, @extended)
AutoIt_Debugger_SendVariable("$lol", $lol, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 23, False, @error, @extended)
	Local $an = "9abcdefghijklmnopqrstuvwxyz| .=-\)(*&^%{}$#@!~/+,'"":;><?[]_ABCDEFGHIJKLMNOPQRSTUVWXYZ012345678"
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 23, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 24, False, @error, @extended)
	$an = $a1 & $an & $a2
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 24, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$a1", $a1, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$a2", $a2, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 25, False, @error, @extended)
	If StringLen($lol) > 0 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 25, False, @error, @extended)
AutoIt_Debugger_SendVariable("$lol", $lol, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 26, False, @error, @extended)
		For $i = 1 To StringLen($lol)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 26, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$lol", $lol, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 27, False, @error, @extended)
			$an = StringReplace($an, StringMid($lol, $i, 1), "", 0, 1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 27, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$lol", $lol, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
;~ 			FileWrite("data.dat",Binary($an))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 29, False, @error, @extended)
		Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 29, False, @error, @extended)
;~ 		ConsoleWrite($an & @lf)

AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 32, False, @error, @extended)
		$ant = StringLeft($an, 35) & $lol & StringRight($an, (StringLen($an) - 35))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 32, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ant", $ant, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$lol", $lol, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 33, False, @error, @extended)
		$an = $ant
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 33, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$ant", $ant, @error, @extended)
;~ 		ConsoleWrite($an & @lf)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 35, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 35, False, @error, @extended)
;~ 	FileWrite("an.txt", Binary($an))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 37, False, @error, @extended)
	$rt = ""
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 37, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 38, False, @error, @extended)
	$rt1 = ""
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 38, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt1", $rt1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 39, False, @error, @extended)
	For $i = 1 To StringLen($pt)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 39, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$pt", $pt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 40, False, @error, @extended)
		$cl = StringMid($pt, $i, 1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 40, False, @error, @extended)
AutoIt_Debugger_SendVariable("$cl", $cl, @error, @extended)
AutoIt_Debugger_SendVariable("$pt", $pt, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 41, False, @error, @extended)
		$cp = StringInStr($an, $cl, 1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 41, False, @error, @extended)
AutoIt_Debugger_SendVariable("$cp", $cp, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$cl", $cl, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 42, False, @error, @extended)
		$idk = $cp + 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 42, False, @error, @extended)
AutoIt_Debugger_SendVariable("$idk", $idk, @error, @extended)
AutoIt_Debugger_SendVariable("$cp", $cp, @error, @extended)
;~ 		ConsoleWrite($cl & @LF & $cp & @LF & $an & @LF)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 44, False, @error, @extended)
		If $cp = StringLen($an) Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 44, False, @error, @extended)
AutoIt_Debugger_SendVariable("$cp", $cp, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 45, False, @error, @extended)
			$rt = $rt & StringLeft($an, 1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 45, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
;~ 			ConsoleWrite("$rt " & $rt & @LF)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 47, False, @error, @extended)
		Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 47, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 48, False, @error, @extended)
			$idk = $cp + 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 48, False, @error, @extended)
AutoIt_Debugger_SendVariable("$idk", $idk, @error, @extended)
AutoIt_Debugger_SendVariable("$cp", $cp, @error, @extended)
;~ 			ConsoleWrite("$idk " & $idk & @LF)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 50, False, @error, @extended)
			$le = StringMid($an, $idk, 1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 50, False, @error, @extended)
AutoIt_Debugger_SendVariable("$le", $le, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$idk", $idk, @error, @extended)
;~ 			ConsoleWrite("$le " & $le & @LF)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 52, False, @error, @extended)
			$rt = $rt & $le
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 52, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_SendVariable("$le", $le, @error, @extended)
;~ 			ConsoleWrite("$rtlol " & $rt & @LF)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 54, False, @error, @extended)
		EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 54, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 55, False, @error, @extended)
	Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 55, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 56, False, @error, @extended)
	For $i = 1 To StringLen($rt)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 56, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 57, False, @error, @extended)
		$ctl = StringMid($rt, $i, 1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 57, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ctl", $ctl, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
;~ 		ConsoleWrite("$ctl " & $ctl & @LF)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 59, False, @error, @extended)
		If $rt1 = "" Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 59, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt1", $rt1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 60, False, @error, @extended)
			$rt1 = $rt1 & StringInStr($an, $ctl, 1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 60, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt1", $rt1, @error, @extended)
AutoIt_Debugger_SendVariable("$rt1", $rt1, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$ctl", $ctl, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 61, False, @error, @extended)
		Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 61, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 62, False, @error, @extended)
			$rt1 = $rt1 & " " & StringInStr($an, $ctl, 1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 62, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt1", $rt1, @error, @extended)
AutoIt_Debugger_SendVariable("$rt1", $rt1, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$ctl", $ctl, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 63, False, @error, @extended)
		EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 63, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 64, False, @error, @extended)
	Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 64, False, @error, @extended)
;~ 	ConsoleWrite("$rt1 " & $rt1 & @LF)
;~ 	ConsoleWrite("$rt " & $rt & @LF)
;~ 	ConsoleWrite("$rt1 " & $rt1 & @LF)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 68, False, @error, @extended)
	$rt = $rt1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 68, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_SendVariable("$rt1", $rt1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 69, False, @error, @extended)
	Return $rt
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 69, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 70, False, @error, @extended)
EndFunc   ;==>sen
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 70, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 71, False, @error, @extended)
Func sde($et, $lol = "")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 71, False, @error, @extended)
AutoIt_Debugger_SendVariable("$et", $et, @error, @extended)
AutoIt_Debugger_SendVariable("$lol", $lol, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 72, False, @error, @extended)
	Local $an = "9abcdefghijklmnopqrstuvwxyz| .=-\)(*&^%{}$#@!~/+,'"":;><?[]_ABCDEFGHIJKLMNOPQRSTUVWXYZ012345678"
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 72, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 73, False, @error, @extended)
	$an = $a1 & $an & $a2
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 73, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$a1", $a1, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$a2", $a2, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 74, False, @error, @extended)
	If StringLen($lol) > 0 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 74, False, @error, @extended)
AutoIt_Debugger_SendVariable("$lol", $lol, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 75, False, @error, @extended)
		For $i = 1 To StringLen($lol)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 75, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$lol", $lol, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 76, False, @error, @extended)
			$an = StringReplace($an, StringMid($lol, $i, 1), "", 0, 1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 76, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$lol", $lol, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
;~ 			FileWrite("data.dat",Binary($an))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 78, False, @error, @extended)
		Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 78, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 79, False, @error, @extended)
		ConsoleWrite($an & @LF)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 79, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)

AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 81, False, @error, @extended)
		$ant = StringLeft($an, 35) & $lol & StringRight($an, (StringLen($an) - 35))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 81, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ant", $ant, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$lol", $lol, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
;~ 		FileWrite("data.dat",Binary($an))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 83, False, @error, @extended)
		$an = $ant
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 83, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$ant", $ant, @error, @extended)
;~ 		FileWrite("data.dat",Binary($an))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 85, False, @error, @extended)
		ConsoleWrite($an & @LF)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 85, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 86, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 86, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 87, False, @error, @extended)
	$rt = ""
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 87, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 88, False, @error, @extended)
	$rt1 = ""
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 88, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt1", $rt1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 89, False, @error, @extended)
	$pt = ""
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 89, False, @error, @extended)
AutoIt_Debugger_SendVariable("$pt", $pt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 90, False, @error, @extended)
	$et = StringReplace($et, @CR, " ")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 90, False, @error, @extended)
AutoIt_Debugger_SendVariable("$et", $et, @error, @extended)
AutoIt_Debugger_SendVariable("$et", $et, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 91, False, @error, @extended)
	$et = StringReplace($et, @LF, " ")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 91, False, @error, @extended)
AutoIt_Debugger_SendVariable("$et", $et, @error, @extended)
AutoIt_Debugger_SendVariable("$et", $et, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 92, False, @error, @extended)
	$et = StringReplace($et, @CRLF, " ")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 92, False, @error, @extended)
AutoIt_Debugger_SendVariable("$et", $et, @error, @extended)
AutoIt_Debugger_SendVariable("$et", $et, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 93, False, @error, @extended)
	$ets = StringSplit($et, " ")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 93, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ets", $ets, @error, @extended)
AutoIt_Debugger_SendVariable("$et", $et, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 94, False, @error, @extended)
	For $i = 1 To $ets[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 94, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$ets", $ets, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 95, False, @error, @extended)
		If $ets[$i] = 1 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 95, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ets", $ets, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 96, False, @error, @extended)
			$rt = $rt & StringRight($an, 1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 96, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 97, False, @error, @extended)
		Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 97, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 98, False, @error, @extended)
			$rt = $rt & StringMid($an, $ets[$i] - 1, 1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 98, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$ets", $ets, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 99, False, @error, @extended)
		EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 99, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 100, False, @error, @extended)
	Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 100, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 101, False, @error, @extended)
	Return binary($rt)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 101, False, @error, @extended)
AutoIt_Debugger_SendVariable("$rt", $rt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 102, False, @error, @extended)
EndFunc   ;==>sde
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\PixelSoftsvn\arcade\em.au3", "em", 102, False, @error, @extended)
