$TempOriginalFileBeingDebuggedFileName = "wrapper"
$TempOriginalFileBeingDebuggedFileFolder = "D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade"
$TempOriginalFileBeingDebuggedFilePath = "D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3"
AutoIt_Debugger_LoadFile("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper")
AutoIt_Debugger_DebugFile(@ScriptFullPath)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 1, False, @error, @extended)
#include-once
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 1, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 2, False, @error, @extended)
#Include "D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\Debug\em.Debug Script.au3"
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 2, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 3, False, @error, @extended)
#Include "D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\Debug\wpa.Debug Script.au3"
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 3, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 4, False, @error, @extended)
#Include "D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\Debug\dstore.Debug Script.au3"
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 4, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 5, False, @error, @extended)
TCPStartup()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 5, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 6, False, @error, @extended)
Local $time
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 6, False, @error, @extended)
AutoIt_Debugger_SendVariable("$time", $time, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 7, False, @error, @extended)
Local $lk
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 7, False, @error, @extended)
AutoIt_Debugger_SendVariable("$lk", $lk, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 8, False, @error, @extended)
Local $reg
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 8, False, @error, @extended)
AutoIt_Debugger_SendVariable("$reg", $reg, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 9, False, @error, @extended)
Local $ek
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 9, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 10, False, @error, @extended)
Local $trial
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 10, False, @error, @extended)
AutoIt_Debugger_SendVariable("$trial", $trial, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 11, False, @error, @extended)
Local $an
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 11, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 12, False, @error, @extended)
Local $tty
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 12, False, @error, @extended)
AutoIt_Debugger_SendVariable("$tty", $tty, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 13, False, @error, @extended)
Local $tt
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 13, False, @error, @extended)
AutoIt_Debugger_SendVariable("$tt", $tt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 14, False, @error, @extended)
Local $guis[16277715]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 14, False, @error, @extended)
AutoIt_Debugger_SendVariable("$guis", $guis, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 15, False, @error, @extended)
Local $ip
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 15, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ip", $ip, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 16, False, @error, @extended)
Global $regged
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 16, False, @error, @extended)
AutoIt_Debugger_SendVariable("$regged", $regged, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 17, False, @error, @extended)
Local $port
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 17, False, @error, @extended)
AutoIt_Debugger_SendVariable("$port", $port, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 18, False, @error, @extended)
Local $ds
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 18, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 19, False, @error, @extended)
$guis[0] = 0
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 19, False, @error, @extended)
AutoIt_Debugger_SendVariable("$guis", $guis, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 20, False, @error, @extended)
Func wrap($an1, $lk1, $ek1, $tt, $tty1, $ip1, $port1)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 20, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an1", $an1, @error, @extended)
AutoIt_Debugger_SendVariable("$lk1", $lk1, @error, @extended)
AutoIt_Debugger_SendVariable("$ek1", $ek1, @error, @extended)
AutoIt_Debugger_SendVariable("$tt", $tt, @error, @extended)
AutoIt_Debugger_SendVariable("$tty1", $tty1, @error, @extended)
AutoIt_Debugger_SendVariable("$ip1", $ip1, @error, @extended)
AutoIt_Debugger_SendVariable("$port1", $port1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 21, False, @error, @extended)
	$regged = 0
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 21, False, @error, @extended)
AutoIt_Debugger_SendVariable("$regged", $regged, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 22, False, @error, @extended)
	$ip = $ip1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 22, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ip", $ip, @error, @extended)
AutoIt_Debugger_SendVariable("$ip1", $ip1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 23, False, @error, @extended)
	$an = $an1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 23, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$an1", $an1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 24, False, @error, @extended)
	$ek = $ek1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 24, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_SendVariable("$ek1", $ek1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 25, False, @error, @extended)
	$lk = $lk1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 25, False, @error, @extended)
AutoIt_Debugger_SendVariable("$lk", $lk, @error, @extended)
AutoIt_Debugger_SendVariable("$lk1", $lk1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 26, False, @error, @extended)
	$tty = $tty1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 26, False, @error, @extended)
AutoIt_Debugger_SendVariable("$tty", $tty, @error, @extended)
AutoIt_Debugger_SendVariable("$tty1", $tty1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 27, False, @error, @extended)
	$port = $port1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 27, False, @error, @extended)
AutoIt_Debugger_SendVariable("$port", $port, @error, @extended)
AutoIt_Debugger_SendVariable("$port1", $port1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 28, False, @error, @extended)
	$reg = "HKLM\Software\Anthrax Interactive\" & $an
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 28, False, @error, @extended)
AutoIt_Debugger_SendVariable("$reg", $reg, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 29, False, @error, @extended)
	$ds = BinaryToString(sde(FileRead("DRM.dat"), $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 29, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
;~ 	$lkey = RegRead($reg, "key")
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 31, False, @error, @extended)
	$lkey = _dstoregetvalue($ds, "key")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 31, False, @error, @extended)
AutoIt_Debugger_SendVariable("$lkey", $lkey, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 32, False, @error, @extended)
	If $lkey = "trial" Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 32, False, @error, @extended)
AutoIt_Debugger_SendVariable("$lkey", $lkey, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 33, False, @error, @extended)
		$trial = 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 33, False, @error, @extended)
AutoIt_Debugger_SendVariable("$trial", $trial, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 34, False, @error, @extended)
		start()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 34, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 35, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 35, False, @error, @extended)
	;msgbox(0, "lk1", $lkey)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 37, False, @error, @extended)
	Local $timeleft1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 37, False, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 38, False, @error, @extended)
	$ftc = ftccheck()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 38, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ftc", $ftc, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 39, False, @error, @extended)
	ConsoleWrite($ftc & @LF)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 39, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ftc", $ftc, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 40, False, @error, @extended)
	If $ftc = 0 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 40, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ftc", $ftc, @error, @extended)
;~ 		$ftc = RegWrite($reg, "ftc", "REG_SZ", "1")
		;msgbox(0,"ftctty",$tty)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 43, False, @error, @extended)
		If $tty = "h" Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 43, False, @error, @extended)
AutoIt_Debugger_SendVariable("$tty", $tty, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 44, False, @error, @extended)
			$timeleft1 = ($tt * 60) * 60
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 44, False, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$tt", $tt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 45, False, @error, @extended)
			$timeleft1 = $timeleft1 & "000"
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 45, False, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
;~ 			RegWrite($reg, "tleft", "REG_SZ", sen($timeleft1, $ek))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 47, False, @error, @extended)
			$ds = _dstorestorevalue($ds, "tleft", sen($timeleft1, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 47, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
			;msgbox(0,"ftcds",$ds)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 49, False, @error, @extended)
			FileDelete("DRM.dat")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 49, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 50, False, @error, @extended)
			FileWrite("DRM.dat", sen($ds, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 50, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 51, False, @error, @extended)
		ElseIf $tty = "m" Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 51, False, @error, @extended)
AutoIt_Debugger_SendVariable("$tty", $tty, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 52, False, @error, @extended)
			$timeleft1 = $tt * 60
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 52, False, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$tt", $tt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 53, False, @error, @extended)
			$timeleft1 = $timeleft1 & "000"
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 53, False, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
;~ 			RegWrite($reg, "tleft", "REG_SZ", sen($timeleft1, $ek))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 55, False, @error, @extended)
			$ds = _dstorestorevalue($ds, "tleft", sen($timeleft1, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 55, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
			;msgbox(0,"ftcds",$ds)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 57, False, @error, @extended)
			FileDelete("DRM.dat")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 57, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 58, False, @error, @extended)
			FileWrite("DRM.dat", sen($ds, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 58, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 59, False, @error, @extended)
		ElseIf $tty = "s" Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 59, False, @error, @extended)
AutoIt_Debugger_SendVariable("$tty", $tty, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 60, False, @error, @extended)
			$timeleft1 = $tt
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 60, False, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$tt", $tt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 61, False, @error, @extended)
			$timeleft1 = $timeleft1 & "000"
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 61, False, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
;~ 			RegWrite($reg, "tleft", "REG_SZ", sen($timeleft1, $ek))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 63, False, @error, @extended)
			$ds = _dstorestorevalue($ds, "tleft", sen($timeleft1, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 63, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
			;msgbox(0,"ftcds",$ds)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 65, False, @error, @extended)
			FileDelete("DRM.dat")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 65, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 66, False, @error, @extended)
			FileWrite("DRM.dat", sen($ds, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 66, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 67, False, @error, @extended)
		ElseIf $tty = "d" Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 67, False, @error, @extended)
AutoIt_Debugger_SendVariable("$tty", $tty, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 68, False, @error, @extended)
			$timeleft1 = ($tt * 60) * 24
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 68, False, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$tt", $tt, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 69, False, @error, @extended)
			$timeleft1 = $timeleft1 & "000"
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 69, False, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
;~ 			RegWrite($reg, "tleft", "REG_SZ", sen($timeleft1, $ek))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 71, False, @error, @extended)
			$ds = _dstorestorevalue($ds, "tleft", sen($timeleft1, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 71, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$timeleft1", $timeleft1, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
			;msgbox(0,"ftcds",$ds)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 73, False, @error, @extended)
			FileDelete("DRM.dat")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 73, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 74, False, @error, @extended)
			FileWrite("DRM.dat", sen($ds, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 74, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 75, False, @error, @extended)
		EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 75, False, @error, @extended)
;~ 		RegWrite($reg, "key", "REG_SZ", "TRIAL")
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 77, False, @error, @extended)
		$ds = _dstorestorevalue($ds, "key", "TRIAL")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 77, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 78, False, @error, @extended)
		FileDelete("DRM.dat")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 78, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 79, False, @error, @extended)
		FileWrite("DRM.dat", sen($ds, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 79, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
		;msgbox(0,"","ts")
		;$trial = 1
		;start()
;~ 		ShellExecute($TempOriginalFileBeingDebuggedFilePath)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 84, False, @error, @extended)
		wrap($an, $lk, $ek, $tt, $tty, $ip, $port)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 84, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$lk", $lk, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_SendVariable("$tt", $tt, @error, @extended)
AutoIt_Debugger_SendVariable("$tty", $tty, @error, @extended)
AutoIt_Debugger_SendVariable("$ip", $ip, @error, @extended)
AutoIt_Debugger_SendVariable("$port", $port, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 85, False, @error, @extended)
		Return
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 85, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 86, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 86, False, @error, @extended)
;~ 	$tlc = sde(RegRead($reg, "tleft"), $ek)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 88, False, @error, @extended)
	$tlc = BinaryToString(sde(_dstoregetvalue($ds, "tleft"), $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 88, False, @error, @extended)
AutoIt_Debugger_SendVariable("$tlc", $tlc, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 89, False, @error, @extended)
	ConsoleWrite("tlc " & $tlc & @LF)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 89, False, @error, @extended)
AutoIt_Debugger_SendVariable("$tlc", $tlc, @error, @extended)
;~ 	;msgbox(0, "", $lkey)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 91, False, @error, @extended)
	If $tlc <= 0 And $lkey = "TRIAL" Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 91, False, @error, @extended)
AutoIt_Debugger_SendVariable("$tlc", $tlc, @error, @extended)
AutoIt_Debugger_SendVariable("$lkey", $lkey, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 92, False, @error, @extended)
		$lkey = InputBox("Enter License", "Trail is over! Please enter your license key")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 92, False, @error, @extended)
AutoIt_Debugger_SendVariable("$lkey", $lkey, @error, @extended)
;~ 		RegWrite($reg, "key", "REG_SZ", sen($lkey, $ek))
;~ 		;msgbox(0, "", $lkey)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 95, False, @error, @extended)
		$ds = _dstorestorevalue($ds, "key", sen($lkey, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 95, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$lkey", $lkey, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
;~ 		;msgbox(0, "", $ds)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 97, False, @error, @extended)
		FileDelete("DRM.dat")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 97, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 98, False, @error, @extended)
		FileWrite("DRM.dat", sen($ds, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 98, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 99, False, @error, @extended)
		wrap($an, $lk, $ek, $tt, $tty, $ip, $port)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 99, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$lk", $lk, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_SendVariable("$tt", $tt, @error, @extended)
AutoIt_Debugger_SendVariable("$tty", $tty, @error, @extended)
AutoIt_Debugger_SendVariable("$ip", $ip, @error, @extended)
AutoIt_Debugger_SendVariable("$port", $port, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 100, False, @error, @extended)
		Return
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 100, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 101, False, @error, @extended)
	ElseIf $lkey = "TRIAL" Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 101, False, @error, @extended)
AutoIt_Debugger_SendVariable("$lkey", $lkey, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 102, False, @error, @extended)
		start()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 102, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 103, False, @error, @extended)
		Return
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 103, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 104, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 104, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 105, False, @error, @extended)
	validate()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 105, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 106, False, @error, @extended)
	start()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 106, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 107, False, @error, @extended)
	Return
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 107, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 108, False, @error, @extended)
EndFunc   ;==>wrap
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 108, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 109, False, @error, @extended)
Func start()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 109, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 110, False, @error, @extended)
	If $trial = 1 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 110, False, @error, @extended)
AutoIt_Debugger_SendVariable("$trial", $trial, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 111, False, @error, @extended)
		$time = TimerInit()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 111, False, @error, @extended)
AutoIt_Debugger_SendVariable("$time", $time, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 112, False, @error, @extended)
		AdlibEnable("timecheck", 1000)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 112, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 113, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 113, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 114, False, @error, @extended)
EndFunc   ;==>start
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 114, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 115, False, @error, @extended)
Func timecheck()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 115, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 116, False, @error, @extended)
	$ctime = TimerDiff($time)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 116, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ctime", $ctime, @error, @extended)
AutoIt_Debugger_SendVariable("$time", $time, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 117, False, @error, @extended)
	ConsoleWrite("ctime " & $ctime & @LF)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 117, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ctime", $ctime, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 118, False, @error, @extended)
	Do
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 118, False, @error, @extended)
;~ 		$otl = BinaryToString(sde(RegRead($reg, "tleft"), $ek))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 120, False, @error, @extended)
		$otl = BinaryToString(sde(_dstoregetvalue($ds, "tleft"), $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 120, False, @error, @extended)
AutoIt_Debugger_SendVariable("$otl", $otl, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
;~ 		ConsoleWrite("otl " & $otl & @LF)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 122, False, @error, @extended)
	Until $otl <> ""
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 122, False, @error, @extended)
AutoIt_Debugger_SendVariable("$otl", $otl, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 123, False, @error, @extended)
	ConsoleWrite("otl " & $otl & @LF)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 123, False, @error, @extended)
AutoIt_Debugger_SendVariable("$otl", $otl, @error, @extended)
;~ 	RegWrite($reg, "tleft", "REG_SZ", sen($otl - $ctime, $ek))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 125, False, @error, @extended)
	$ds = _dstorestorevalue($ds, "tleft", sen($otl - $ctime, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 125, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$otl", $otl, @error, @extended)
AutoIt_Debugger_SendVariable("$ctime", $ctime, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 126, False, @error, @extended)
	FileDelete("DRM.dat")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 126, False, @error, @extended)
;~ 	;msgbox(0,"",$ds)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 128, False, @error, @extended)
	FileWrite("DRM.dat", sen($ds, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 128, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 129, False, @error, @extended)
	$time = TimerInit()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 129, False, @error, @extended)
AutoIt_Debugger_SendVariable("$time", $time, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 130, False, @error, @extended)
	$otl = $otl - $ctime
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 130, False, @error, @extended)
AutoIt_Debugger_SendVariable("$otl", $otl, @error, @extended)
AutoIt_Debugger_SendVariable("$otl", $otl, @error, @extended)
AutoIt_Debugger_SendVariable("$ctime", $ctime, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 131, False, @error, @extended)
	If 0 > $otl Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 131, False, @error, @extended)
AutoIt_Debugger_SendVariable("$otl", $otl, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 132, False, @error, @extended)
		validate()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 132, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 133, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 133, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 134, False, @error, @extended)
EndFunc   ;==>timecheck
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 134, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 135, False, @error, @extended)
Func isserialvalid($serial)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 135, False, @error, @extended)
AutoIt_Debugger_SendVariable("$serial", $serial, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 136, False, @error, @extended)
	$s = TCPConnect($ip, $port)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 136, False, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
AutoIt_Debugger_SendVariable("$ip", $ip, @error, @extended)
AutoIt_Debugger_SendVariable("$port", $port, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 137, False, @error, @extended)
	ConsoleWrite("ip " & $ip & @LF)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 137, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ip", $ip, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 138, False, @error, @extended)
	If $s = -1 Or @error Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 138, False, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
		;msgbox(0, $s & " | " & @error, "OMG :O THERE WAS A ERROR CONTACT ANTHRAX INTERASCTIVE IMMIDIATLY WITH ERRORID: servdown | " & $ip)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 140, False, @error, @extended)
		Return _dstoregetvalue($ds, "ltsv")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 140, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 141, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 141, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 142, False, @error, @extended)
	TCPSend($s, sen("VALID|" & $an & "|" & $serial, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 142, False, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$serial", $serial, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 143, False, @error, @extended)
	$data = ""
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 143, False, @error, @extended)
AutoIt_Debugger_SendVariable("$data", $data, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 144, False, @error, @extended)
	Do
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 144, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 145, False, @error, @extended)
		$data = $data & BinaryToString(sde(TCPRecv($s, 2048), $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 145, False, @error, @extended)
AutoIt_Debugger_SendVariable("$data", $data, @error, @extended)
AutoIt_Debugger_SendVariable("$data", $data, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 146, False, @error, @extended)
	Until $data <> ""
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 146, False, @error, @extended)
AutoIt_Debugger_SendVariable("$data", $data, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 147, False, @error, @extended)
	$ds = _dstorestorevalue($ds, "ltsv", $data)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 147, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$data", $data, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 148, False, @error, @extended)
	FileDelete("DRM.dat")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 148, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 149, False, @error, @extended)
	FileWrite("DRM.dat", sen($ds, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 149, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 150, False, @error, @extended)
	TCPCloseSocket($s)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 150, False, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 151, False, @error, @extended)
	$s = -1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 151, False, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 152, False, @error, @extended)
	Return $data
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 152, False, @error, @extended)
AutoIt_Debugger_SendVariable("$data", $data, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 153, False, @error, @extended)
EndFunc   ;==>isserialvalid
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 153, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 154, False, @error, @extended)
Func ftccheck()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 154, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 155, False, @error, @extended)
	$s = TCPConnect($ip, $port)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 155, False, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
AutoIt_Debugger_SendVariable("$ip", $ip, @error, @extended)
AutoIt_Debugger_SendVariable("$port", $port, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 156, False, @error, @extended)
	ConsoleWrite("ip " & $ip & @LF)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 156, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ip", $ip, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 157, False, @error, @extended)
	If $s = -1 Or @error Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 157, False, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
		;msgbox(0, $s & " | " & @error, "OMG :O THERE WAS A ERROR CONTACT ANTHRAX INTERASCTIVE IMMIDIATLY WITH ERRORID: servdown | " & $ip)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 159, False, @error, @extended)
		Return 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 159, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 160, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 160, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 161, False, @error, @extended)
	TCPSend($s, sen("FTC|" & $an & "|" & getpk(), $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 161, False, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 162, False, @error, @extended)
	$data = ""
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 162, False, @error, @extended)
AutoIt_Debugger_SendVariable("$data", $data, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 163, False, @error, @extended)
	Do
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 163, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 164, False, @error, @extended)
		$data = $data & BinaryToString(sde(TCPRecv($s, 2048), $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 164, False, @error, @extended)
AutoIt_Debugger_SendVariable("$data", $data, @error, @extended)
AutoIt_Debugger_SendVariable("$data", $data, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 165, False, @error, @extended)
	Until $data <> ""
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 165, False, @error, @extended)
AutoIt_Debugger_SendVariable("$data", $data, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 166, False, @error, @extended)
	TCPCloseSocket($s)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 166, False, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 167, False, @error, @extended)
	$s = -1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 167, False, @error, @extended)
AutoIt_Debugger_SendVariable("$s", $s, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 168, False, @error, @extended)
	Return $data
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 168, False, @error, @extended)
AutoIt_Debugger_SendVariable("$data", $data, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 169, False, @error, @extended)
EndFunc   ;==>ftccheck
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 169, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 170, False, @error, @extended)
Func validate()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 170, False, @error, @extended)
;~ 	$lkey = sde(RegRead($reg, "key"), $ek)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 172, False, @error, @extended)
	$lkey = BinaryToString(sde(_dstoregetvalue($ds, "key"), $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 172, False, @error, @extended)
AutoIt_Debugger_SendVariable("$lkey", $lkey, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 173, False, @error, @extended)
	$var = isserialvalid($lkey)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 173, False, @error, @extended)
AutoIt_Debugger_SendVariable("$var", $var, @error, @extended)
AutoIt_Debugger_SendVariable("$lkey", $lkey, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 174, False, @error, @extended)
	If $var = 1 Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 174, False, @error, @extended)
AutoIt_Debugger_SendVariable("$var", $var, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 175, False, @error, @extended)
		$regged = 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 175, False, @error, @extended)
AutoIt_Debugger_SendVariable("$regged", $regged, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 176, False, @error, @extended)
		AdlibDisable()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 176, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 177, False, @error, @extended)
		Return
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 177, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 178, False, @error, @extended)
	Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 178, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 179, False, @error, @extended)
		If $lkey = $lk Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 179, False, @error, @extended)
AutoIt_Debugger_SendVariable("$lkey", $lkey, @error, @extended)
AutoIt_Debugger_SendVariable("$lk", $lk, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 180, False, @error, @extended)
			$regged = 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 180, False, @error, @extended)
AutoIt_Debugger_SendVariable("$regged", $regged, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 181, False, @error, @extended)
			AdlibDisable()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 181, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 182, False, @error, @extended)
			Return
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 182, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 183, False, @error, @extended)
		Else
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 183, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 184, False, @error, @extended)
			For $i = 1 To $guis[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 184, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$guis", $guis, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 185, False, @error, @extended)
				GUISetState(@SW_HIDE, $guis[$i])
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 185, False, @error, @extended)
AutoIt_Debugger_SendVariable("$guis", $guis, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 186, False, @error, @extended)
			Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 186, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 187, False, @error, @extended)
			$lkey = InputBox("Enter License", "Invalid license or trial is over! Please enter your license key")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 187, False, @error, @extended)
AutoIt_Debugger_SendVariable("$lkey", $lkey, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 188, False, @error, @extended)
			If @error Then
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 188, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 189, False, @error, @extended)
				Exit
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 189, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 190, False, @error, @extended)
			EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 190, False, @error, @extended)
;~ 			RegWrite($reg, "key", "REG_SZ", sen($lkey, $ek))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 192, False, @error, @extended)
			$ds = _dstorestorevalue($ds, "key", sen($lkey, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 192, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$lkey", $lkey, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 193, False, @error, @extended)
			FileDelete("DRM.dat")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 193, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 194, False, @error, @extended)
			FileWrite("DRM.dat", sen($ds, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 194, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
;~ 			;msgbox(0,"vds",$ds)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 196, False, @error, @extended)
			AdlibDisable()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 196, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 197, False, @error, @extended)
			For $i = 1 To $guis[0]
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 197, False, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_SendVariable("$guis", $guis, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 198, False, @error, @extended)
				GUISetState(@SW_SHOW, $guis[$i])
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 198, False, @error, @extended)
AutoIt_Debugger_SendVariable("$guis", $guis, @error, @extended)
AutoIt_Debugger_SendVariable("$i", $i, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 199, False, @error, @extended)
			Next
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 199, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 200, False, @error, @extended)
			wrap($an, $lk, $ek, $tt, $tty, $ip, $port)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 200, False, @error, @extended)
AutoIt_Debugger_SendVariable("$an", $an, @error, @extended)
AutoIt_Debugger_SendVariable("$lk", $lk, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_SendVariable("$tt", $tt, @error, @extended)
AutoIt_Debugger_SendVariable("$tty", $tty, @error, @extended)
AutoIt_Debugger_SendVariable("$ip", $ip, @error, @extended)
AutoIt_Debugger_SendVariable("$port", $port, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 201, False, @error, @extended)
			Return
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 201, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 202, False, @error, @extended)
		EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 202, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 203, False, @error, @extended)
	EndIf
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 203, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 204, False, @error, @extended)
EndFunc   ;==>validate
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 204, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 205, False, @error, @extended)
Func regnow($serial)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 205, False, @error, @extended)
AutoIt_Debugger_SendVariable("$serial", $serial, @error, @extended)
;~ 	RegWrite($reg, "key", "REG_SZ", sen($serial, $ek))
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 207, False, @error, @extended)
	$ds = _dstorestorevalue($ds, "key", sen($serial, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 207, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$serial", $serial, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 208, False, @error, @extended)
	FileDelete("DRM.dat")
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 208, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 209, False, @error, @extended)
	FileWrite("DRM.dat", sen($ds, $ek))
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 209, False, @error, @extended)
AutoIt_Debugger_SendVariable("$ds", $ds, @error, @extended)
AutoIt_Debugger_SendVariable("$ek", $ek, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 210, False, @error, @extended)
	validate()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 210, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 211, False, @error, @extended)
	Return
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 211, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 212, False, @error, @extended)
EndFunc   ;==>regnow
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 212, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 213, False, @error, @extended)
Func reggui($handle)
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 213, False, @error, @extended)
AutoIt_Debugger_SendVariable("$handle", $handle, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 214, False, @error, @extended)
	$guis[0] = $guis[0] + 1
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 214, False, @error, @extended)
AutoIt_Debugger_SendVariable("$guis", $guis, @error, @extended)
AutoIt_Debugger_SendVariable("$guis", $guis, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 215, False, @error, @extended)
	$guis[$guis[0]] = $handle
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 215, False, @error, @extended)
AutoIt_Debugger_SendVariable("$guis", $guis, @error, @extended)
AutoIt_Debugger_SendVariable("$guis", $guis, @error, @extended)
AutoIt_Debugger_SendVariable("$handle", $handle, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 216, False, @error, @extended)
EndFunc   ;==>reggui
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 216, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 217, False, @error, @extended)
Func getpk()
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 217, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 218, False, @error, @extended)
	Return _WPA_DecodeProductKey(_WPA_getBinaryDPID_WINDOWS())
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 218, False, @error, @extended)
AutoIt_Debugger_NextLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 219, False, @error, @extended)
EndFunc   ;==>getpk
AutoIt_Debugger_FinishedLine("D:\Documents and Settings\Maverick\Desktop\thumb\anthraxsvn\arcade\wrapper.au3", "wrapper", 219, False, @error, @extended)
